BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "CLIENTE" (
	"ID_CLIENTE"	INTEGER NOT NULL UNIQUE,
	"CPF"	INTEGER NOT NULL UNIQUE,
	"EMAIL"	TEXT NOT NULL UNIQUE,
	"SENHA"	TEXT NOT NULL,
	"NOME"	TEXT NOT NULL,
	PRIMARY KEY("ID_CLIENTE")
);
CREATE TABLE IF NOT EXISTS "CONTA" (
	"NUMERO_CONTA"	INTEGER NOT NULL UNIQUE,
	"DIGITO_CONTA"	INTEGER NOT NULL,
	"NUMERO_AGENCIA"	INTEGER,
	"FK_ID_CLIENTE"	INTEGER NOT NULL,
	FOREIGN KEY("FK_ID_CLIENTE") REFERENCES "CLIENTE"("ID_CLIENTE"),
	PRIMARY KEY("NUMERO_CONTA" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TRANSACAO" (
	"ID_TRANSACAO"	INTEGER NOT NULL UNIQUE,
	"DESCRICAO"	TEXT,
	"VALOR"	NUMERIC NOT NULL,
	"DATA"	NUMERIC NOT NULL,
	"TIPO_TRANSACAO"	TEXT NOT NULL,
	"FK_NUMERO_CONTA"	TEXT NOT NULL,
	FOREIGN KEY("FK_NUMERO_CONTA") REFERENCES "CONTA"("NUMERO_CONTA"),
	PRIMARY KEY("ID_TRANSACAO" AUTOINCREMENT)
);
COMMIT;
